version: "3.9"

services:

  adguardhome:
    container_name: ${CONTAINER_PREFIX}adguardhome
    image: adguard/adguardhome:latest
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "3000:3000/tcp"
    volumes:
      - ${CONFIG_PATH}/adguardhome/conf:/opt/adguardhome/conf
      - ${CONFIG_PATH}/adguardhome/work:/opt/adguardhome/work
    environment:
      - TZ=${TZ}
    restart: ${RESTART_POLICY}

  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: ${CONTAINER_PREFIX}homepage
    environment:
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "3001:3000"
    restart: ${RESTART_POLICY}

  watchtower:
    image: containrrr/watchtower
    container_name: ${CONTAINER_PREFIX}watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    environment:
      - TZ=${TZ}
      - WATCHTOWER_SCHEDULE=0 0 4 * * *  # Update at 4 AM daily
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=false
    restart: always
